electrostore/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('user/login/', views.uslogin, name='uslogin'),
    path('logout/', views.uslogout, name='uslogout'),
    path('accounts/profile/', views.authemail, name='authemail'),  # CUSTOM
    path('myapp/', include('myapp.urls')),
    path('auth/', include('social_django.urls', namespace='social')),
    path('paypal/', include('paypal.standard.ipn.urls')),

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)+static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

myapp/urls.py
from django.urls import path
from myapp import views

app_name='myapp'
 
urlpatterns = [
    path('usregister/',views.usregister,name='usregister'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('uservalid/',views.uservalid,name='uservalid'),
    path('about/',views.about,name='about'),
    path('showproducts/',views.showproducts,name='showproducts'),
    path('singleproduct/',views.singleproduct,name='singleproduct'),
    path('mail/',views.usermail,name='mail'),
    path('base/',views.base,name='base'),
    path('cart/',views.addcart,name='cart'),
    path('removecart/',views.removeCart,name='removecart'),
    path('grandTotal/',views.grandTotal,name='grandTotal'),
    path('sendMail/',views.sendMail,name='sendMail'),
    path('success_payment/',views.success_payment, name='success_payment'),
    path('get_order/',views.get_order, name='get_order'),
    path('orders/',views.orders, name='orders'),
    path('pending_orders/',views.pending_orders, name='pending_orders'),
    path('profile/',views.profile, name='profile'),
    path('change_profile/',views.change_profile, name='change_profile'),
    path('singleorder/',views.singleorder, name='singleorder'),
    path('change_password/',views.change_password, name='change_password'),
    path('order_detail/',views.order_detail, name='order_detail'),
]

templates/about.html
{% extends "base.html" %} {% load static %} {% block body %}
<!-- banner -->
<div class="banner banner10">
  <div class="container">
    <h2>About Us</h2>
  </div>
</div>
<!-- //banner -->
<!-- breadcrumbs -->
<div class="breadcrumb_dress">
  <div class="container">
    <ul>
      <li>
        <a href="{% url 'index'%}"
          ><span class="glyphicon glyphicon-home" aria-hidden="true"></span>
          Home</a
        >
        <i>/</i>
      </li>
      <li>About Us</li>
    </ul>
  </div>
</div>
<!-- //breadcrumbs -->
<!-- about -->
<div class="about">
  <div class="container">
    <div class="w3ls_about_grids">
      <div class="col-md-6 w3ls_about_grid_left">
        <p>
          Cheap deals and better prices are available online, because products
          come to you direct from the manufacturer or seller without involving
          middlemen.
        </p>
        <div class="col-xs-2 w3ls_about_grid_left1">
          <span
            class="glyphicon glyphicon-new-window"
            aria-hidden="true"
          ></span>
        </div>
        <div class="col-xs-10 w3ls_about_grid_left2">
          <p>
            Admin module is basically for the owner of the system. Admin of
            website can login and help the Users. It can manage site content.
            Admin can edit, delete Pages and Comments. It also manages users of
            website. Admin can approve or reject the privileges. Admin can add
            or delete the products from the store. But the main function of this
            module is to handle security of this system. Different types of
            authentication and authorization process is performed for this
            purpose.
          </p>
        </div>
        <div class="clearfix"></div>
        <div class="col-xs-2 w3ls_about_grid_left1">
          <span class="glyphicon glyphicon-flash" aria-hidden="true"></span>
        </div>
        <div class="col-xs-10 w3ls_about_grid_left2">
          <p>
            You get to try things on in the comfort of your own home. It
            comprises of two users the one who sells its products & other is the
            buyer. The seller & the buyer must have username and password to
            login into website. The seller must register itself in order to make
            its products visible to the buyer. The buyer can only make a final
            purchase if it is registered and has all the information stored in
            its profile.
          </p>
        </div>
        <div class="clearfix"></div>
      </div>
      <div class="col-md-6 w3ls_about_grid_right">
        <img
          src="{% static 'images/52.jpg' %}"
          alt=" "
          class="img-responsive"
        />
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
<!-- //about -->
<!-- team -->
<div class="team">
  <div class="container">
    <h3>Meet Our Team</h3>
    <div class="wthree_team_grids">
      <div class="col-md-3 wthree_team_grid">
        <img src="{% static 'images/t4.png'%}" alt=" " class="img-responsive" />
        <h4>Smith Allen <span>Manager</span></h4>
        <div class="agileits_social_button">
          <!-- <ul>
                        <li><a href="#" class="facebook"> </a></li>
                        <li><a href="#" class="twitter"> </a></li>
                        <li><a href="#" class="google"> </a></li>
                        <li><a href="#" class="pinterest"> </a></li>
                    </ul> -->
        </div>
      </div>
      <div class="col-md-3 wthree_team_grid">
        <img src="{% static 'images/t5.png'%}" alt=" " class="img-responsive" />
        <h4>Laura James <span>Designer</span></h4>
        <div class="agileits_social_button">
          <!-- <ul>
                        <li><a href="#" class="facebook"> </a></li>
                        <li><a href="#" class="twitter"> </a></li>
                        <li><a href="#" class="google"> </a></li>
                        <li><a href="#" class="pinterest"> </a></li>
                    </ul> -->
        </div>
      </div>
      <div class="col-md-3 wthree_team_grid">
        <img src="{% static 'images/t6.png'%}" alt=" " class="img-responsive" />
        <h4>Crisp Doe <span>Director</span></h4>
        <div class="agileits_social_button">
          <!-- <ul>
                        <li><a href="#" class="facebook"> </a></li>
                        <li><a href="#" class="twitter"> </a></li>
                        <li><a href="#" class="google"> </a></li>
                        <li><a href="#" class="pinterest"> </a></li>
                    </ul> -->
        </div>
      </div>
      <div class="col-md-3 wthree_team_grid">
        <img src="{% static 'images/t7.png'%}" alt=" " class="img-responsive" />
        <h4>Linda Rosy <span>Quality Checker</span></h4>
        <div class="agileits_social_button">
          <!-- <ul>
                        <li><a href="#" class="facebook"> </a></li>
                        <li><a href="#" class="twitter"> </a></li>
                        <li><a href="#" class="google"> </a></li>
                        <li><a href="#" class="pinterest"> </a></li>
                    </ul> -->
        </div>
      </div>
      <div class="clearfix"></div>
      <p>
        a team member could be one of several institutional investors trading
        the asset markets together, or a business person working closely with
        others within their company.
      </p>
    </div>
  </div>
</div>
<!-- //team -->
<!-- team-bottom -->
<div class="team-bottom">
  <div class="container">
    <h3>Are You Ready For Deals? Flat <span>30% Offer </span>on Mobiles</h3>
    <p>
      Exclusive Electronics Deals..!!Start here Sign in and see... Top deals in
      electronic accessories. All Available here
    </p>
    <a href="{% url 'myapp:showproducts' %}">Shop Now</a>
  </div>
</div>
<!-- //team-bottom -->
{% endblock %}

templates/cart.html
{% extends "dashboard.html" %} {% load static %} {% block content %}
<style>
  .spinnerouter {
    background: rgb(0, 0, 0, 0.5);
    position: fixed;
    width: 100%;
    height: 100%;
    z-index: 99999;
    top: 0px;
    display: none;
  }
  .loader {
    border: 16px solid #f3f3f3; /* Light grey */
    border-top: 16px solid rgb(60, 67, 164); /* Blue */
    border-radius: 50%;
    width: 120px;
    height: 120px;
    animation: spin 1s linear infinite;
    position: absolute;
    left: 45%;
    top: 45%;
    z-index: 999999;
  }
  .spinner-border {
    height: 25px;
    width: 25px;
    border: 5px solid white;
    border-top: 5px solid #f0ad4e;
    animation: spin 1s linear infinite;
    border-radius: 50%;
    margin: auto;
  }
  @keyframes spin {
    0% {
      transform: rotate(0deg);
    }
    100% {
      transform: rotate(360deg);
    }
  }
  table,
  td {
    color: black !important;
  }
</style>
<div class="spinnerouter">
  <div class="loader"></div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-12">
      {% if messages %} {% for i in messages %}
      <div class="alert alert-{{i.tags}} status">{{i}}</div>
      {% endfor %} {% endif %}
    </div>

    <div class="col-md-12" style="" id="empty">
      {% if cart_size is 0 %}
      <h2>❌ Your Shopping Cart is Empty</h2>
      {% else %}
    </div>
    {% if user.is_authenticated %} {% if user.is_superuser %}
    <div class="col-md-12">
      <h2>Sorry as you are admin, You are not allowed here!!!</h2>
    </div>
    {% else %}
    <div class="col-md-7">
      <h2>My Cart(<span id="csize">{{cart_size}}</span> )</h2>
      <hr />
      <ul class="list-group">
        {% for i in cart %}
        <li
          class="list-group-item c-{{i.id}}"
          style="box-shadow: 0px 0px 10px black"
        >
          <div class="row">
            <div class="col-md-3" style="text-align: center; font-size: 30px">
              <span>
                <img
                  src="/media/{{i.photo}}"
                  style="border-radius: 50%; margin: 10px"
                  height="70"
                  width="70"
                  class="rounded-circle"
                />
                <div class="form-group">
                  <div class="row">
                    <div class="col-md-3 col-sm-3 col-3">
                      <span onclick="addNum('{{i.id}}','add')">
                        <i class="fas fa-plus-circle text-success"></i>
                      </span>
                    </div>
                    <div class="col-md-6 col-sm-6 col-6">
                      <input
                        type="number"
                        id="num"
                        value="{{i.quantity}}"
                        class="form-control num{{i.id}}"
                      />
                    </div>
                    <div class="col-md-3 col-sm-3 col-3">
                      <span onclick="addNum('{{i.id}}','sub')">
                        <i class="fas fa-minus-circle text-danger"></i>
                      </span>
                    </div>
                  </div>
                </div>
              </span>
            </div>
            <div class="col-md-9">
              <span class="text-danger font-weight-bold">
                <strong>{{i.product_name}}</strong><br />
                |{{i.product_cat}} | {{i.brand}}
              </span>
              <h4 style="margin-top: 20px">
                <strong class="text-success cartsaleprice{{i.id}}"
                  >&#8377;{{i.price}}</strong
                >
                <del style="font-size: 12px" class="cartprice{{i.id}}">
                  &#8377; {{i.market}}</del
                >
                <span style="color: green; font-family: arial"
                  >You save {{i.offer}}%</span
                >
              </h4>
            </div>
          </div>
          <hr />
        </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col-md-4">
      {% if cart_size is not 0 %}
      <h2>Price Details</h2>
      <hr />
      <div style="border: 1px solid gray; padding: 10px; border-radius: 5px">
        <table class="table">
          <tbody>
            <tr>
              <td id="itotal">ITEM TOTAL</td>
              <td id="total"></td>
            </tr>
            <tr style="border-bottom: 1px dotted gray">
              <td>DELIVERY CHARGES</td>
              <td>FREE</td>
            </tr>
            <tr>
              <td><strong>GRAND TOTAL</strong></td>
              <td id="grand"></td>
            </tr>
          </tbody>
        </table>
        <hr />
        <div style="padding: 10px; display: none" id="delivery_address">
          <h4>Enter Delivery Details</h4>
          <hr />

          <div class="form-group">
            <input
              type="text"
              class="form-control"
              placeholder="Enter Name"
              id="dname"
              required
            />
          </div>
          <div class="form-group">
            <!-- <label for="" id='res'></label> -->
            <input
              type="email"
              class="form-control"
              placeholder="Enter Email Address"
              id="demail"
              required
            />
          </div>
          <!-- <div class='form-group' style='display:none;'>
                                <input type="number" class='form-control' placeholder='Enter OTP Here' id='id_enter_otp'>
                            </div> -->
          <div class="form-group">
            <input
              type="number"
              class="form-control"
              placeholder="Enter Mobile Number"
              id="dnumber"
              required
            />
          </div>
          <div class="form-group">
            <textarea
              name="daddress"
              id="daddress"
              class="form-control"
              placeholder="Enter Full Address"
              required
            ></textarea>
          </div>
          <div class="form-group">
            <input type="hidden" id="grandtotal" />
            <input type="hidden" id="items" value="{{cids}}" />
            <button class="btn btn-success btn-block" id="ptp">
              Proceed To Pay
            </button>
          </div>
        </div>
        <button class="btn btn-warning btn-block" id="ptb">
          <i class="fas fa-shopping-cart"></i> Proceed To Buy
        </button>
      </div>
      {% endif %}
    </div>
    {% endif %} {% endif %} {% endif %}
  </div>
</div>
<script>
  function addNum(id, action) {
    $(".spinnerouter").show();
    let v = $(".num" + id).val();
    let updateQuant = 0;
    if (action == "add") {
      updateQuant = parseInt(v) + 1;
    } else {
      updateQuant = parseInt(v) - 1;
    }
    setTimeout(function () {
      $.ajax({
        url: '{% url "myapp:cart" %}',
        type: "get",
        data: { q: updateQuant, id: id },
        success: function (data) {
          $(".num" + id).val(data.quantity);
          $(".cartsaleprice" + id).html(data.sale_price * data.quantity);
          $(".cartprice" + id).html(data.price * data.quantity);
          $(".spinnerouter").hide();
          $("#csize").html(data.cart_size);
          grandTotal();

          // #Remove Items
          if (data.quantity == 0) {
            $.ajax({
              url: '{% url "myapp:removecart" %}',
              data: { removeid: id },
              success: function (data) {
                $(".c-" + id).hide();
                $(".status").html(data.msz);
                $("#csize").html(data.cart_size);
              },
            });
          }
        },
      });
    });
  }
</script>

<script>
  let email;
  function grandTotal() {
    $.ajax({
      url: '{% url "myapp:grandTotal" %}',
      success: function (data) {
        $("#itotal").html("ITEM TOTAL (" + data.quantity + ")");
        $("#total").html("&#8377;" + data.grand_total);
        $("#grand").html("&#8377;" + data.grand_total);
        $("#demail").val(data.email);
        $("#dname").val(data.name);
        $("#daddress").val(data.address);
        $("#grandtotal").val(data.grand_total);
        $("#ptp").html("Proceed To Pay &#8377;" + data.grand_total);
      },
    });
  }
  grandTotal();
</script>
<script>
  $("#ptb").click(function () {
    $(this).html('<div class="spinner-border"></div>');
    setTimeout(function () {
      $("#delivery_address").slideDown(1000);
      $("#ptb").hide();
    }, 1500);
  });
</script>

<!-- VERIFICATION EMAIL -->
<script>
  var arr = [];
  $("#dnu").focus(function () {
    var name = $("#dname").val();
    var email = $("#demail").val();
    $.ajax({
      url: '{% url "myapp:sendMail"%}',
      data: { name: name, email: email },
      success: function (data) {
        arr = data.split("@");
        $("#res").html(arr[0]).addClass("text-success");
        $("#id_enter_OTP").show();
      },
    });
  });
</script>

<script>
  $("#ptp").click(function () {
    let dname = $("#dname").val();
    let demail = $("#demail").val();
    let daddr = $("#daddress").val();
    let dcon = $("#dnumber").val();
    let amount = $("#grandtotal").val();
    let it = $("#items").val();
    $.ajax({
      url: '{% url "myapp:get_order"%}',
      type: "get",
      data: {
        grandtotal: amount,
        dname: dname,
        demail: demail,
        daddress: daddr,
        dnumber: dcon,
        items: it,
      },
      success: function (data) {
        let oid =
          parseInt(data) + Math.round(Math.random() * (9999 - 1000) + 1000);
        url =
          "http://sachtechsolution.pe.hu/easypayment/payment.php?mid=qHwSXt13054106235849&amount=" +
          amount +
          "&adminemail=amandeepit02@gmail.com&adminmobile=7837494347&mkey=g3iLvlGhNj4Iahwo&orderid=" +
          data +
          "o" +
          oid +
          '&returnurl=http://127.0.0.1:8000{% url "myapp:success_payment" %}';
        window.location = url;
      },
    });
  });
</script>
{% endblock %}

templates/change_password.html
{% extends 'dashboard.html'%}
{% block content %}
<style>
    label,::placeholder{
        color:gray !important;
    }

</style>
<div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto p-5" style="background:#fff;">
                {% if status %}
                    <p class='alert alert-success m-3'>
                        <i class='fas fa-check'></i> {{status}}</p>
                {% endif %}
                <h2>Change Password</h2>
                <div style='height:2px;width:100px;background:#ff5063'></div>
                <p class='my-1'>
                    Fill out the details to change your account password
                </p>
                <form action="{% url 'myapp:change_password' %}" method="post" class='mt-4'>
                    {% csrf_token %}
                    <input type="hidden" name='id' value='{{pp.id}}'>
                    {% if messages %}
                        <ul class='messages'>
                            {% for message in messages %}
                                <li class='{{message.tags}}'>{{message}}
                                <a href="{% url 'index'%}">Login Again</a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% endif %}
                    <div class='form-group'>
                        <label>Current Password</label>
                        <input placeholder="Current Password" type="password" class="form-control" name="oldpass" />
                   </div>
                    <div class='form-group'>
                        <div class="row">
                            <div class="col-md-6">
                                <label>New Password</label>
                                <input name='newpass' placeholder="New Password" type="password" class="form-control" id='pass' onkeyup="checkpass()"/>
                            </div>
                            <div class="col-md-6">
                                <label>Re-enter New Password</label>
                                <input placeholder="Re-enter New Password" type="password" class="form-control" id='cpass' onkeyup="checkpass()"/>
                            </div>
                        </div>
                    </div>
                    <div class='form-group'>
                        <input type="submit" id='submit' class="btn btn-block text-light" style='border-radius:20px;background:#ff5063;' value='Change Password'/>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
    function checkpass(){
        let p = $('#pass').val();
        let cp = $('#cpass').val();
        if(p==cp){
            $('#pass').css('border','1px solid green');
            $('#cpass').css('border','1px solid green');
            $('#submit').removeAttr('disabled');
        }else{
            $('#pass').css('border','1px solid red');
            $('#cpass').css('border','1px solid red');
            $('#submit').attr('disabled','disabled');
        }
    }
    </script>
{% endblock %}

templates/change_profile.html
{% extends 'dashboard.html'%}
{% block content %}
<style>
    label,::placeholder{
        color:gray !important;
    }

</style>
<div class="container">
        <div class="row">
            <div class="col-md-8 mx-auto p-5" style="background:#fff;">
                {% if status %}
                    <p class='alert alert-success m-3'>
                        <i class='fas fa-check'></i> {{status}}</p>
                {% endif %}
                <h2>Change Profile</h2>
                <div style='height:2px;width:100px;background:#ff5063'></div>
                <p class='my-1'>
                    Fill your details here. If you change your email, use updated email for further loggin in.
                </p>
                <form action="{% url 'myapp:change_profile' %}" method="post" class='mt-4'>
                    {% csrf_token %}
                    <input type="hidden" name='id' value='{{pp.id}}'>
                    <input type="hidden" name='custid' value='{{pp.custid}}'>
                    <div class='form-group'>
                        <div class="row">
                            <div class="col-md-3">
                                <label>Subtitle</label>
                                <input name='subtitle' placeholder="{{pp.subtitle}}" type="text" class="form-control"/>
                            </div>
                            <div class="col-md-9">
                                <label>Name</label>
                                <input placeholder="{{pp.first_name}}"t type="text" class="form-control" name="name" />
                            </div>
                        </div>
                    </div>
                   <div class='form-group'>
                        <label>Email</label>
                        <input placeholder="{{pp.username}}" type="email" class="form-control" name="email" />
                   </div>
                    <div class='form-group'>
                        <label for="">Address</label>
                        <textarea placeholder="{{pp.address}}" class="form-control" name="address"></textarea>
                    </div>
                    <div class='form-group'>
                        <input type="submit" class="btn btn-block text-light" style='border-radius:20px;background:#ff5063;'/>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/dashboard.html
{% extends "base.html"%} {% load static%} {% block style %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
<link rel="stylesheet" href="{% static 'mystyle.css'%}" />

{% endblock %} {% block body %}
<div class="container-fluid" style="overflow-x: hidden">
  <div class="row">
    <div class="col-md-2">
      {% if user.is_authenticated %} {% if user.is_superuser %} {% else %}
      <div class="ab pt-2">
        <img
          src="/media/{{pp.profile_pic}}"
          class="dash-img"
          style="height: 80px; width: 80px; border-radius: 50%"
        />
        <p>
          <a href="{% url 'myapp:profile'%}">
            {{pp.subtitle}} {{user.first_name}}</a
          >
        </p>
      </div>
      <div class="ab list-group">
        <h4 class="title">
          <i class="far fa-address-card"></i> Manage Profile
        </h4>
        <a href="{% url 'myapp:profile'%}" class="list-group-item dash"
          >My Profile</a
        >
        <a href="{% url 'myapp:change_profile' %}" class="list-group-item dash"
          >Change Profile</a
        >
        <a href="{% url 'myapp:change_password' %}" class="list-group-item dash"
          >Change Password</a
        >
      </div>
      <div class="ab">
        <h4 class="title"><i class="fas fa-cart-arrow-down"></i> My Orders</h4>
        <a href="{% url 'myapp:orders'%}" class="list-group-item dash"
          >Order History</a
        >
        <a href="{% url 'myapp:pending_orders'%}" class="list-group-item dash"
          >Pending Orders</a
        >
      </div>
      <div class="ab">
        <h4 class="title">
          <a href="{% url 'uslogout'%}" class="list-group-item dash"
            ><i class="fas fa-sign-out-alt"></i> Logout</a
          >
        </h4>
      </div>
      {% endif %} {% endif %}
    </div>
    <div class="col-md-9" id="rcover">{% block content %} {% endblock %}</div>
  </div>
</div>
{% endblock %}

templates/mail.html
{% extends "base.html" %}
{% block body %}

{% if status %}
<script>
alert('Thanks Mr./Miss {{name}} for your feedback!!! It is really beneficial for us!!!');
</script>
{% endif %}
<!-- banner -->
<div class="banner banner10">
    <div class="container">
        <h2>Contact Us</h2>
    </div>
</div>
<!-- //banner -->    
<!-- breadcrumbs -->
<div class="breadcrumb_dress">
    <div class="container">
        <ul>
            <li><a href="{% url 'index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> Home</a> <i>/</i></li>
            <li>Contact Us</li>
        </ul>
    </div>
</div>
<!-- //breadcrumbs --> 
<!-- mail -->
<div class="mail">
    <div class="container">
        <h3>Contact Us</h3>
        <div class="agile_mail_grids">
            <div class="col-md-5 contact-left">
                <h4>Address</h4>
                <p>#C-86, Phase 7, Industrial Area, Sector 74, <br/>      
                    <span>SAS Nagar, Punjab 160055</span></p>
                <ul>
                    <li>Free Phone :+91-8283828598 </li>
                    <li>Telephone :+91-7087425488</li>
                    <li><a href="">info@sachtechsolution.com</a></li>
                </ul>
            </div>
            <div class="col-md-7 contact-left">
                <h4>Contact Form</h4>
                <form action="" method="post">
                    {% csrf_token %}
                    <input type="text" name="Name" placeholder="Your Name" required="" minlength="3" pattern="[A-Za-zs\]+" title="Must Contain Character Only With No Spaces">
                    <input type="email" name="Email" placeholder="Your Email" required="">
                    <input type="text" name="Telephone" placeholder="Telephone No" required="" min="1000000000" max="9999999999">
                    <textarea name="message" placeholder="Message..." required=""></textarea>
                    <input type="submit" value="Submit" >
                </form>
            </div>
            <div class="clearfix"> </div>
        </div>

        <div class="contact-bottom">
            <iframe height='250' src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d13720.221241693445!2d76.6859110243319!3d30.71684544048498!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390fee5c15850793%3A0x462f369a90d12231!2sSachTech+Solution!5e0!3m2!1sen!2sin!4v1550405500684" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
    </div>
</div>

{% endblock %}

templates/orderes.html
{% extends "dashboard.html" %} {% load static%} {% block style %}
<link
  rel="stylesheet"
  href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"
/>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
<link rel="stylesheet" href="{% static 'mystyle.css'%}" />
<style>
  .ab {
    border: 1px solid black !important;
  }
</style>
{% endblock %} {% block content %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
<h2 class="py-5">Order History</h2>
<table class="table table-striped table-hover table-bordered" id="myTable">
  <thead>
    <tr>
      <th>Order ID</th>
      <th>Total Price</th>
      <th>Received On</th>
      <th>Processed On</th>
      <th>Payment Mode</th>
      <th>View Items</th>
    </tr>
  </thead>
  <tbody>
    {% for i in all_orders %}
    <tr>
      <td>{{i.id}}</td>
      <td>{{i.amount}}</td>
      <td>{{i.received_on}}</td>
      <td>{{i.changed_on}}</td>
      <td>{{i.payment_mode}}</td>
      <td>
        <a href="{% url 'myapp:order_detail'%}?id={{i.id}}"
          ><button id="" class="btn btn-sm btn-primary">View</button></a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script>
  $(function () {
    $("#myTable").DataTable();
  });
</script>
{% endblock %}

templates/pending.html
{% extends "dashboard.html" %} {% load static%} {% block style %}
<link
  rel="stylesheet"
  href="//cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css"
/>
<script src="//cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
<link rel="stylesheet" href="{% static 'mystyle.css'%}" />
<style>
  .ab {
    border: 1px solid black !important;
  }
</style>
{% endblock %} {% block content %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}" />
<h2 class="py-5">Pending Orders</h2>
<table class="table table-striped table-hover table-bordered" id="myTable">
  <thead>
    <tr>
      <th>Order ID</th>
      <th>Total Price</th>
      <th>Received On</th>
      <th>Processed On</th>
      <th>View Items</th>
    </tr>
  </thead>
  <tbody>
    {% for i in pending_orders %}
    <tr>
      <td>{{i.id}}</td>
      <td>{{i.amount}}</td>
      <td>{{i.received_on}}</td>
      <td>{{i.changed_on}}</td>
      <td>
        <a href="{% url 'myapp:order_detail'%}?id={{i.id}}"
          ><button id="" class="btn btn-sm btn-primary">View</button></a
        >
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<script>
  $(function () {
    $("#myTable").DataTable();
  });
</script>
{% endblock %}